### PR TITLE
Repo cleanup

### PR DESCRIPTION
**Pull request by TSC21**
This pretends to do a major cleanup on the repository, mainly removing containers and scripting that is outdated or seem to be out of use:
1. ROS Indigo containers (Indigo is EOL);
2. Gstreamer containers (*gstreamer1.0*  is already installed in PX4 base containers;
3. Remove the scripts folder as those should be contained, or in the devguide, or in a specific repository.

### CODE REVIEW

**Comment by TSC21** [comment]
@AndreasAntener I kept the Vagrant stuff, but they probably need to be reviewed and updated. Do you have the bandwidth to do it? Thank you

**Comment by dagar** [comment]
Most of the non-container content of this repo predates me.

Given how tied these containers are to particular PX4/Firmware version (many dependencies installed from a script that now lives in PX4/Firmware) should we just consolidate in tree?

**Comment by TSC21** [comment]
> Given how tied these containers are to particular PX4/Firmware version (many dependencies installed from a script that now lives in PX4/Firmware) should we just consolidate in tree?

I am not sure I get you. What kind of consolidation are you looking for?

**Comment by TSC21** [comment]
> > Given how tied these containers are to particular PX4/Firmware version (many dependencies installed from a script that now lives in PX4/Firmware) should we just consolidate in tree?
> 
> I am not sure I get you. What kind of consolidation are you looking for?

OK so you want to move the containers to the PX4 Firmware tree? As a submodule maybe?

**Comment by TSC21** [comment]
I will merge this at the end of the day if there are no objections.

**Comment by julianoes** [comment]
Dockerhub complains:
```
Building in Docker Cloud's infrastructure...
Cloning into '.'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
Switched to a new branch 'repo_cleanup'
Build path does not exist: ./docker/px4-dev/Dockerfile_base-xenial
```

**Comment by lamping7** [comment]
That makes sense. All of the paths for each container in DockerHub need to be changed to reflect this.

**Comment by TSC21** [comment]
> Dockerhub complains:
> 
> ```
> Building in Docker Cloud's infrastructure...
> Cloning into '.'...
> Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
> Switched to a new branch 'repo_cleanup'
> Build path does not exist: ./docker/px4-dev/Dockerfile_base-xenial
> ```

Yes, those paths we not changed yet. That will be done after this gets merged.

**Pull request merged**
