### PR TITLE
workflows: build xenial-base using Github actions

### PR DESCRIPTION
**Pull request by julianoes**
Let's try to use this instead of building on dockerhub.

### CODE REVIEW

**Comment by TSC21** [comment]
@julianoes is there a specific reason we are moving to Github Actions?

**Comment by julianoes** [comment]
@TSC21 I just wanted to experiment if that could be faster and more transparent. The way via dockerhub is slow and hard to understand.

**Comment by julianoes** [comment]
This now works for the two base images. The question is how this could work for images on top of the base image. The problem is that we reference the tag in the Dockerfile but that tag has not been built yet. So essentially we can't reference thebase in the pull request as it will always fail. We could reference to `latest` and push to `latest` in a PR but then different PRs would conflict.

An alternative would be not to build anything in the PR and then build it all using `latest` once merged to master.

**Comment by TSC21** [comment]
@julianoes I don't really like the idea of using the `latest` tag, but if there's no other solution, we might have to use it.

**Comment by julianoes** [comment]
@TSC21 I lean towards building everything on master but not in the pull request.

**Pull request merged**
