### PR TITLE
Base px4-dev-ros from px4-dev-simulation (Ubuntu 18.04)

### PR DESCRIPTION
**Pull request by TSC21**
It does not make much sense to have the ROS containers independent of the simulation ones, specially when one pretends to use them for testing ROS routines/missions in the simulation environment.

### CODE REVIEW

**Comment by dagar** [comment]
I believe at some point there was a conflict between gazebo versions in simulation (standalone gazebo) and ROS (gazebo from ROS packages.

**Comment by TSC21** [comment]
That shouldn't be the case now.

**Comment by TSC21** [comment]
@julianoes you know what may be causing this http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/feature%2Fros_dependent_of_simulation/8/pipeline#step-56-log-185? I tried to fix it with 93ea860 but no luck.

**Comment by TSC21** [comment]
Bringing this in as the error is not related.

**Pull request merged**
