### PR TITLE
Adds px4tools to docker image to make CI build faster.

### PR DESCRIPTION
**Pull request by jgoppert**

### CODE REVIEW

**Comment by jgoppert** [comment]
@dagar @LorenzMeier @AndreasAntener This is adding about 4 min to our current CI builds since it needs to build pandas from source to get the latest time series handling from pandas which is required for the groundtruth error analysis px4tools is doing.

**Comment by dagar** [comment]
Thanks, this is good for now, but I'll also add it to the base docker image as I go through restructuring them.
Right now jenkins is pulling the 1.0 tag of px4-dev-ros, so we'll need to update that as well.

**Comment by LorenzMeier** [comment]
@dagar Can you try to update that now and see if CI passes? Since I've re-tuned the airframes things might be overall more stable now.

**Comment by dagar** [comment]
Actually, I just realized the way jenkins was temporarily fixed was by using the last "good" px4-dev-ros image from ~6 months ago.

The plan was to get an updated 16.04 image with current gazebo and ros and try jenkins ci again. I can pick away at some of that today.

**Comment by LorenzMeier** [comment]
Yep. But I suspect that the race conditions and bad tuning I fixed this week were the main culprit and that you might be able to just enable auto-building.

**Comment by LorenzMeier** [comment]
@dagar, can we quickly discuss in Gitter or Skype?

**Pull request merged**
