### PR TITLE
ubuntu 16.04 -> 18.04

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by hamishwillee** [comment]
@dagar I guess this means should update all our developer facing scripts and tests everywhere to latest LTS?

**Comment by dagar** [comment]
Unless it's a surprisingly painless transition I might wait a bit. I opened this to get it going on the side.

Ideally I'd like to keep both 16.04 and 18.04 supported if it's realistic if only in a minor capacity. What were you thinking for docs?

**Comment by hamishwillee** [comment]
Docs should mirror docker. If you can support both then so can docs. A good reason to finish the work started in https://github.com/PX4/Firmware/pull/8818 :-).

**Comment by dagar** [comment]
The existing 16.04 environment is working well and tagged. I'm going to merge this to begin wider testing (not updating CI usage yet).
@hamishwillee let's sync up before Firmware officially bumps versions and we'll make sure everything is done simultaneously and consistently.

**Comment by hamishwillee** [comment]
That sounds like a good idea. When is Firmware bumping next? I'm around today and early tomorrow but then will be in the air until Friday. 
I haven't been testing on 18.04 but would be good to know that simulation stuff all works solidly.

I wonder if we should consider versioning the doc set (in the same way as for the dronecode SDK). I know it is another discussion, but would be nice to have and old version that people could refer to for the build environment once we update.

**Pull request merged**
