### PR TITLE
update GNU Arm Embedded Toolchain to 9-2019-q4-major

### PR DESCRIPTION
**Pull request by TSC21**
To give continuity to https://github.com/PX4/Firmware/pull/14159.

### CODE REVIEW

**Comment by bys1123** [comment]
Awesome! And this one also need to update then? 
https://github.com/PX4/Firmware/blob/master/Tools/setup/ubuntu.sh

**Comment by LorenzMeier** [comment]
Wait guys, this first needs proper flight testing. @TSC21 This change is safety critical. It can't be just pushed through!

**Comment by TSC21** [comment]
> Wait guys, this first needs proper flight testing. @TSC21 This change is safety critical. It can't be just pushed through!

@LorenzMeier I know. We are not updating the tags upstream yet. But this makes the container already ready to CI.

**Comment by TSC21** [comment]
https://github.com/PX4/Firmware/issues/14580 was created so that the build binaries generated from the new toolchain version are validated first.

**Pull request merged**
