### PR TITLE
ROS2 Crystal: update Fast-RTPS fastrtpsgen to 1.7.0

### PR DESCRIPTION
**Pull request by TSC21**
Fixes https://github.com/PX4/containers/issues/154, as it is a requirement for building the micro-RTPS bridge in `px4_ros_com`.

### CODE REVIEW

**Comment by TSC21** [comment]
@dagar @julianoes we are having some awkward issue with the `archlinux` container.

**Comment by julianoes** [comment]
Looks like this bug: https://bugs.archlinux.org/task/61428

**Comment by julianoes** [comment]
Unfortunately, they don't have tags for the base images, so we can't use an older image that works.
https://hub.docker.com/r/archlinux/base/tags

**Comment by TSC21** [comment]
@julianoes thanks for researching. That link shared is quite new so I guess this is a new problem as well. We can try to use one of our previous tags for this one? Or it won't make a difference?

**Comment by julianoes** [comment]
> We can try to use one of our previous tags for this one? Or it won't make a difference?

I suppose so.

**Pull request merged**
