### PR TITLE
Add good bad and ugly gstreamer plugins to support camera streaming again

### PR DESCRIPTION
**Pull request by tfoote**
Follow up to: https://github.com/PX4/sitl_gazebo/pull/268 and https://github.com/PX4/sitl_gazebo/pull/148

### CODE REVIEW

**Comment by thomasgubler** [comment]
@hamishwillee @dagar Any idea why this fails at gitbook install?

**Comment by hamishwillee** [comment]
Has the base container changed? Ie is this still Ubuntu 16.04? Docs build doesn't work for later version (yet)

**Comment by dagar** [comment]
@hamishwillee no I don't think it's changed. https://github.com/PX4/containers/blob/master/docker/px4-dev/Dockerfile_docs

**Comment by dagar** [comment]
Here's the last build in master.
http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/master/72/pipeline

image

**Comment by hamishwillee** [comment]
Great. Then not a docs problem - just a temporary glitch. Correct me if I need to look into this some more.

**Comment by tfoote** [comment]
The rebuild seems to have failed on clone later in the process on trying to clone from github:
image

Could someone retrigger again? I'll try a close and reopen to see if that retriggers.

**Comment by tfoote** [comment]
Rebased on master which got a new CI started

**Comment by tfoote** [comment]
@dagar @thomasgubler @hamishwillee I've retriggered this several times and it keeps failing a different way. Is this level of errors expected and should I just keep retrying?

This last build error like this

http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/tfoote-gstreamer/4/pipeline
```
WARNING: Error loading config file: /home/jenkins/.docker/config.json: The Auth config file is empty

Error response from daemon: Container fd84275d67ec703d5066c57050b84840cd516bd137075859094d834e8521c6eb is not running

process apparently never started in /tmp/jenkins/workspace/PX4_containers_tfoote-gstreamer/Firmware@tmp/durable-0483025b

script returned exit code -2
```

**Comment by LorenzMeier** [comment]
@dagar I think we need to prune builds more aggressively.

**Comment by dagar** [comment]
Looking into this.

**Comment by dagar** [comment]
@tfoote could you give this another try after https://github.com/PX4/containers/pull/170 goes through? The fix is the entrypoint in docs.

**Comment by dagar** [comment]
https://github.com/PX4/containers/pull/170 has merged, I'll rebase this PR.

**Pull request merged**
