### PR TITLE
px4-dev: Try to move to Python 3

### PR DESCRIPTION
**Pull request by julianoes**
This goes with https://github.com/PX4/Firmware/pull/12809.

### CODE REVIEW

**Comment by TSC21** [comment]
This will become problematic for the ROS containers.

**Comment by julianoes** [comment]
So how can we get ROS to Python 3? It's 2019...

**Comment by lamping7** [comment]
>So how can we get ROS to Python 3? It's 2019...

You can't (without a major effort). Just because it's EOL, doesn't mean it's obsolete.

**Comment by julianoes** [comment]
Alright but as @dagar suggested we can probably have Python 2 dependencies on higher level containers for ROS.

**Comment by cclauss** [comment]
In this repo, these Python 3 syntax errors should be fixed:
[flake8](http://flake8.pycqa.org) testing of https://github.com/PX4/containers on Python 3.7.1

$ __flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics__
```
./docker/ros-indigo/sitl-testing/scripts/testing/export_charts.py:145:44: E999 SyntaxError: invalid syntax
            print "Exporting chart %s to %s" % (chart["name"], path)
                                           ^
./docker/ros-indigo/mavros/tools/broadcaster.py:46:21: E999 SyntaxError: invalid syntax
            print ":".join("{:02x}".format(ord(c)) for c in buf)
                    ^
2     E999 SyntaxError: invalid syntax
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

**Comment by julianoes** [comment]
@cclauss thanks, see: https://github.com/PX4/containers/pull/200.

**Comment by cclauss** [comment]
Nice!  PX4/Firmware#13008  Today, there are __100 days__ until Python 2 end of life.

> Just because it's EOL, doesn't mean it's obsolete.

Just because it's EOL means that it is _going to become an attack vector_ for evil doers because the Python Software Foundation and Python Core Team have been _very clear_ that they [will not even fix known security vulnerabilities](https://www.python.org/doc/sunset-python-2) discovered after 1/1/2020..

**Comment by TSC21** [comment]
@julianoes what about we keep Python2 together with Python3? I mean, instead of replacing, we duplicate the install steps for Python3

**Comment by julianoes** [comment]
@TSC21 I would like to move to Python 3 as much as possible. Otherwise we'll be stuck with Python 2 forever. I suggest that add whatever Python 2 things are necessary for ROS in the ROS containers.

**Comment by TSC21** [comment]
> @TSC21 I would like to move to Python 3 as much as possible. Otherwise we'll be stuck with Python 2 forever. I suggest that add whatever Python 2 things are necessary for ROS in the ROS containers.

Can we at least keep `python-pip` and `python-setuptools`? If not, can you move it to the simulation containers on this PR?

**Comment by julianoes** [comment]
> Can we at least keep python-pip and python-setuptools?

I wouldn't add dependencies that are not used in the same scope. Otherwise the next person will remove them again because it's not clear why they are there.

Feel free to add commits to add what ROS requires.

**Comment by TSC21** [comment]
> > Can we at least keep python-pip and python-setuptools?
> 
> I wouldn't add dependencies that are not used in the same scope. Otherwise the next person will remove them again because it's not clear why they are there.
> 
> Feel free to add commits to add what ROS requires.

The problem is not just ROS: http://ci.px4.io:8080/blue/organizations/jenkins/PX4%2Fcontainers/detail/PR-199/2/pipeline/#step-104-log-33

**Comment by julianoes** [comment]
Alright, I'll fix it.

**Comment by TSC21** [comment]
@julianoes instead of mutually excluding Python 2 and 3, let's for now keep Python 2 in the container and install Python 3 in parallel. Does that work for you?

**Comment by cclauss** [comment]
With 44 days left until Python 2 end of life, why not put Python 2 in the trash and install Python 3 everywhere?  Python 3 has been in existence for 13+ years.

**Comment by TSC21** [comment]
> With 44 days left until Python 2 end of life, why not put Python 2 in the trash and install Python 3 everywhere? Python 3 has been in existence for 13+ years.

Because we still have a "problem" called ROS ;)

**Comment by TSC21** [comment]
@julianoes I say we give this a shot and let it go through, so we can solve the chicken and egg problem. Then we address whatever it's required. Let's unblock this - can you please set the `master` branch for the Jenkins stages and bring this in? Thanks!

**Comment by julianoes** [comment]
@TSC21 I think we need to release this and create a tag and then reference to this, right?

**Comment by cclauss** [comment]
I thought the Python 3 thing was already solved in ROS...
__apt-get install python3-rospkg python3-rospkg-modules python3-catkin-pkg python3-catkin-pkg-modules__

http://wiki.ros.org/rospkg
http://wiki.ros.org/catkin_pkg
https://index.ros.org/deps/page/22/name/
https://index.ros.org/deps/page/23/name/

**Comment by TSC21** [comment]
> @TSC21 I think we need to release this and create a tag and then reference to this, right?

Yes. Just change the Jenkins stuff and I can do that immediately if you want.

**Comment by TSC21** [comment]
I am merging this now and tagging it so we can solve PX4/Firmware#12809.

**Pull request merged**
