### PR TITLE
Updated for changes qrlSDK and -trim support for installer

### PR DESCRIPTION
**Pull request by mcharleb**
Requires the latest version of cross_toolchain

Signed-off-by: Mark Charlebois <charlebm@gmail.com>

### CODE REVIEW

**Comment by LorenzMeier** [comment]
@dagar Good to go?

**Comment by dagar** [comment]
Likely, but I don't have these SDKs to test with and neither does the build system. Julian has been building and pushing it manually. 
@julianoes could you pull this in locally, build, and push to docker hub? If that succeeds we can merge this PR and I can readd the semaphore snapdragon build.

**Comment by mcharleb** [comment]
@julianoes I am adding a -trim option to qrlinux_sysroot.sh to remove all the runtime cruft and duplicate libs. I will push that today. I've got the qrlSDK install down to about 450MB from 1.3GB.

**Comment by dagar** [comment]
Another important point to mention since we're on the topic of reducing size.
A feature of docker is that each separate line in the build file creates a new layer, and all of these layers end up pushed to docker hub.

In this case it means if you cleanup in a separate step all the previous stuff is still in a layer and it ends up being pushed to docker hub.

Try `docker history px4-dev-snapdragon` (or whatever you call it locally) to see the layers that correspond to each command. I'm not sure how to prevent the bin and tgz files from being cached. Could we pull them in with wget?

**Comment by mcharleb** [comment]
@dagar One option would be to install and trim the SDK and sysroot on the build machine, then tar them up and add them to the docker image. Then the docker image would only have the reduced image and no intermediate files. The docker file would depend on this thing that gets externally created, but it seems like the only way to not bloat the intermedate layers.

**Comment by dagar** [comment]
Yes that could work, but I think you'd have to run it manually before the docker build.

Is there any way we can wget qualcomm_hexagon_sdk_lnx_3_0_eval.bin and qrlSDK.tgz, even if we need to authenticate?
Then a single step becomes wget && install && rm -rf installer and we could automate the build on docker hub, but still keep it private/restricted.

**Comment by mcharleb** [comment]
All you need is a QDN account for qualcomm_hexagon_sdk_lnx_3_0_eval.bin

You have to have a support login (which you get when you register a product) for Intrinsyc to get qrlSDK.tgz

**Comment by mcharleb** [comment]
@dagar I pushed an update that does what I suggested above.

**Comment by julianoes** [comment]
Thanks @mcharleb! I ran a `docker build` and got:
```
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
px4io/px4-dev-snapdragon       latest              5e88f4726e4c        43 seconds ago      1.375 GB
```

Does that match what you have?

**Comment by LorenzMeier** [comment]
@dagar Good to go?

**Comment by LorenzMeier** [comment]
@dagar I can get the files onto protected AWS. Does that allow then to automate this with Docker hub so we can auto-build the trimmed SDK?

**Comment by dagar** [comment]
The URL would still be public in this repo, unless you're thinking of limiting access to docker hub builders?
We could do private github repo for snapdragon DockerFile with corresponding private docker automated build.

**Comment by julianoes** [comment]
I'm happy to push the image that I made, privately, just for CI like previously. But I wanted to check back if I got the correct result size-wise.

**Comment by dagar** [comment]
Moving px4-dev-snapdragon to the standalone repo here - https://github.com/LorenzMeier/px4-dev-snapdragon

**Comment by mcharleb** [comment]
@julianoes  Here is what I get for the ATLFlight px4_base image:

atlflight/px4_base                latest              a0d275006195        5 days ago          1.28 GB

**Pull request closed without merging**
