### PR TITLE
Dockerfile_base, archlinux_install_script: add pyyaml and cerberus python packages

### PR DESCRIPTION
**Pull request by bkueng**
Required for https://github.com/PX4/Firmware/pull/10337

### CODE REVIEW

**Comment by bkueng** [comment]
I don't know what CI is doing but it looks unrelated:
```
/usr/lib/ccache/arm-linux-gnueabihf-g++  -DCONFIG_ARCH_BOARD_BEBOP -D__DF_BEBOP -D__DF_LINUX -D__PX4_LINUX -D__PX4_POSIX -D__PX4_POSIX_BEBOP -D__STDC_FORMAT_MACROS -Dnoreturn_function="__attribute__((noreturn))" -I. -Isrc -Isrc/lib -Isrc/modules -I../../src -I../../src/drivers/boards/bebop -I../../src/include -I../../src/lib -I../../src/lib/DriverFramework/framework/include -I../../src/lib/matrix -I../../src/modules -I../../src/platforms -I../../platforms/posix/include -I../../src/lib/DriverFramework/drivers/mpu6050/../../framework/include -g -fno-exceptions -fno-rtti -std=gnu++11 -fno-threadsafe-statics -DCONFIG_WCHAR_BUILTIN -D__CUSTOM_FILE_IO__ -fcheck-new -Wall -Wextra -Werror -Warray-bounds -Wdisabled-optimization -Wdouble-promotion -Wfatal-errors -Wfloat-equal -Wformat-security -Winit-self -Wlogical-op -Wmissing-declarations -Wpointer-arith -Wshadow -Wuninitialized -Wunknown-pragmas -Wunused-variable -Wno-implicit-fallthrough -Wno-missing-field-initializers -Wno-missing-include-dirs -Wno-unused-parameter -Wunused-but-set-variable -Wformat=1 -Wno-overloaded-virtual -Wreorder -Wno-format-truncation -fvisibility=hidden -include visibility.h -Wno-missing-field-initializers -fno-strict-aliasing -fomit-frame-pointer -fno-math-errno -funsafe-math-optimizations -ffunction-sections -fdata-sections -fno-strength-reduce -fno-builtin-printf -fdiagnostics-color=always -O2 -g -DNDEBUG   -std=gnu++11 -MD -MT src/lib/DriverFramework/drivers/mpu6050/CMakeFiles/df_mpu6050.dir/MPU6050.cpp.o -MF src/lib/DriverFramework/drivers/mpu6050/CMakeFiles/df_mpu6050.dir/MPU6050.cpp.o.d -o src/lib/DriverFramework/drivers/mpu6050/CMakeFiles/df_mpu6050.dir/MPU6050.cpp.o -c ../../src/lib/DriverFramework/drivers/mpu6050/MPU6050.cpp

In file included from ../../src/lib/DriverFramework/framework/include/DriverFramework.hpp:38:0,

                 from ../../src/lib/DriverFramework/drivers/mpu6050/MPU6050.cpp:37:

../../src/lib/DriverFramework/drivers/mpu6050/MPU6050.cpp: In member function 'virtual void DriverFramework::MPU6050::_measure()':

../../src/lib/DriverFramework/drivers/mpu6050/MPU6050.cpp:511:10: error: implicit conversion from 'float' to 'double' when passing argument to function [-Werror=double-promotion]

      fabs(temp_c - _last_temp_c), (double)_last_temp_c, (double)temp_c);

      ~~~~^~~~~~~~~~~~~~~~~~~~~~~

../../src/lib/DriverFramework/framework/include/DFLog.hpp:98:79: note: in definition of macro 'DF_LOG_ERR'

 #define DF_LOG_ERR(FMT, ...)  printf("%" PRIu64 " " FMT "\n", offsetTime(), ##__VA_ARGS__)

                                                                               ^~~~~~~~~~~
```

and:

```
Some packages could not be installed. This may mean that you have

requested an impossible situation or if you are using the unstable

distribution that some required packages have not yet been created

or been moved out of Incoming.

The following information may help to resolve the situation:


The following packages have unmet dependencies:

 gazebo7 : Depends: libboost-filesystem1.58.0 but it is not installable

           Depends: libboost-program-options1.58.0 but it is not installable

           Depends: libboost-regex1.58.0 but it is not installable

           Depends: libboost-system1.58.0 but it is not installable

           Depends: libboost-thread1.58.0 but it is not installable

           Depends: libgazebo7 (= 7.14.0-1~xenial) but it is not going to be installed

           Depends: libprotobuf9v5 but it is not installable

           Depends: libsdformat4 but it is not going to be installed

 libgazebo7-dev : Depends: libsdformat4-dev but it is not going to be installed

                  Depends: libgazebo7 (= 7.14.0-1~xenial) but it is not going to be installed

                  Depends: gazebo7-plugin-base (= 7.14.0-1~xenial) but it is not going to be installed

E: Unable to correct problems, you have held broken packages.
```

---

@MaEtUgR can you add the python packages `pyyaml` and `cerberus` to the cygwin toolchain?

**Comment by dagar** [comment]
The timing is a bit awkward because this is moving to Ubuntu 18.04. If this is needed immediately we may need to do it on a branch right before https://github.com/PX4/containers/commit/65a976b39dc754b85e1759adbd0d01fa1dc092be.

**Comment by dagar** [comment]
Side note - I've been intending to collect all of the actual python dependencies in a requirements.txt that lives in the Firmware repository, which would then be used here and in the docs. https://github.com/PX4/Firmware/blob/master/Tools/setup/requirements.txt

**Comment by dagar** [comment]
I'll merge this now, but we'll either need to finishing moving armhf, snapdragon, etc to 18.04, or branch the last 16.04 version and tag.

**Comment by bkueng** [comment]
> Side note - I've been intending to collect all of the actual python dependencies in a requirements.txt that lives in the Firmware repository, which would then be used here and in the docs.

I already updated that in the PR as well.

> I'll merge this now, but we'll either need to finishing moving armhf, snapdragon, etc to 18.04, or branch the last 16.04 version and tag.

Can we do the branch? I think that's the easiest & fastest way.

**Comment by TSC21** [comment]
Can we update https://github.com/PX4/Firmware/blob/master/.ci/Jenkinsfile-compile with the new tag? For now the latest one is called `pr-gazebo` so I assume this is a dev tag.

**Comment by MaEtUgR** [comment]
@bkueng I skipped `cerberus` because I didn't realize 😬 I presume it's still required. Urgently? Any reference pr to test?

**Comment by bkueng** [comment]
It's required with https://github.com/PX4/Firmware/pull/10337. It's ready to test and should get merged soon.

**Comment by MaEtUgR** [comment]
I finally added the forgoten `cerberus` now: https://github.com/PX4/windows-toolchain/commit/8d399c557ef0721f1ca13d1a899c474312aa1595 will be in the 0.5 setup.

**Pull request merged**
