### PR TITLE
px4-dev-ros update

### PR DESCRIPTION
**Pull request by dagar**

### CODE REVIEW

**Comment by LorenzMeier** [comment]
This looks generally good but it means that we have slightly older versions of e.g. Dronekit.

**Comment by dagar** [comment]
Grab it directly from github?

**Comment by LorenzMeier** [comment]
For Dronekit I'd say yes. For everything else I think going with package management is fine.

**Comment by dagar** [comment]
Dronekit-python now installed from github master in px4-dev-simulation.

**Comment by AndreasAntener** [comment]
Haven't forgotten this btw, I built and tested the ROS container before the dronekit change. But haven't found the issue with the tests yet.

**Comment by AndreasAntener** [comment]
Built again, testing SITL. Something that already annoys me is that the nuttx stuff is not in the SITL container :)

**Comment by dagar** [comment]
You'd want a single image where you can both build nuttx and run sitl with
gazebo and/or jmavsim? Basing px4-dev-simulation and px4-dev-ros by
extension on px4-dev-nuttx instead of base would only add a few hundred
megabytes to these images that are already multigigabyte.
Let me know what works for your use case. I generally try to do everything
"natively" in Ubuntu, but I'd like to start relying on these more and more
so that my local setup always exactly matches what other devs are using and
the binaries that users fly.

**Comment by dagar** [comment]
@AndreasAntener feel free to modify and merge when ready. The latest version of px4-dev-ros isn't really functional, so it's not exactly critical that this branch works perfectly before merging.

**Comment by dagar** [comment]
Great! Size is only a problem for travis-ci/semaphore/circleci that pull the image every single build. If simulation or ros are already on jenkins we can get away with them being enormous.

I assume the mission tests still fail strangely under this new new px4-dev-ros?

**Pull request merged**
