### PR TITLE
Fix and minor cleanup for Python3

### PR DESCRIPTION
**Pull request by julianoes**
Python 3 `print()` and some PEP8 warnings.

### CODE REVIEW

**Comment by julianoes** [comment]
@dagar what's going on with `make clean` here? I don't get it.

**Comment by julianoes** [comment]
Bump @dagar

**Comment by dagar** [comment]
I don't even see a `clean` target in the Makefile. Do you want to gut it and replace with a git clean that always runs in post? Historically it was worth it to prevent the build slaves scratch space from filling up.

**Comment by cclauss** [comment]
The review process seems too long.  Perhaps break this into multiple PRs.
1. A PR to convert the legacy print statements into print() function.
2. A PR to mess with Makefile.
3. A PR with whitespace changes that gets created AFTER 1. has landed.

**Comment by TSC21** [comment]
@julianoes I made some changes in the Jenkinsfile that fix your problem with the `make` command. Please rebase.

**Comment by julianoes** [comment]
Thanks @TSC21, I rebased.

**Pull request merged**
